/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace ViolationLogger {
  export type ViolationStruct = {
    userId: string;
    userName: string;
    action: string;
    permissionsInToken: string;
    timestamp: BigNumberish;
    reportedBy: AddressLike;
  };

  export type ViolationStructOutput = [
    userId: string,
    userName: string,
    action: string,
    permissionsInToken: string,
    timestamp: bigint,
    reportedBy: string
  ] & {
    userId: string;
    userName: string;
    action: string;
    permissionsInToken: string;
    timestamp: bigint;
    reportedBy: string;
  };
}

export interface ViolationLoggerInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addAuditor"
      | "auditors"
      | "getAllViolations"
      | "getTotalViolations"
      | "getViolationsByUser"
      | "owner"
      | "recordViolation"
      | "removeAuditor"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AuditorAdded"
      | "AuditorRemoved"
      | "ViolationRecorded"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "addAuditor",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "auditors",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getAllViolations",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getTotalViolations",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getViolationsByUser",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "recordViolation",
    values: [string, string, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "removeAuditor",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "addAuditor", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "auditors", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getAllViolations",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTotalViolations",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getViolationsByUser",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "recordViolation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeAuditor",
    data: BytesLike
  ): Result;
}

export namespace AuditorAddedEvent {
  export type InputTuple = [auditor: AddressLike];
  export type OutputTuple = [auditor: string];
  export interface OutputObject {
    auditor: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AuditorRemovedEvent {
  export type InputTuple = [auditor: AddressLike];
  export type OutputTuple = [auditor: string];
  export interface OutputObject {
    auditor: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ViolationRecordedEvent {
  export type InputTuple = [
    userId: string,
    action: string,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [userId: string, action: string, timestamp: bigint];
  export interface OutputObject {
    userId: string;
    action: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ViolationLogger extends BaseContract {
  connect(runner?: ContractRunner | null): ViolationLogger;
  waitForDeployment(): Promise<this>;

  interface: ViolationLoggerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addAuditor: TypedContractMethod<
    [_auditor: AddressLike],
    [void],
    "nonpayable"
  >;

  auditors: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  getAllViolations: TypedContractMethod<
    [],
    [ViolationLogger.ViolationStructOutput[]],
    "view"
  >;

  getTotalViolations: TypedContractMethod<[], [bigint], "view">;

  getViolationsByUser: TypedContractMethod<
    [_userId: string],
    [ViolationLogger.ViolationStructOutput[]],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  recordViolation: TypedContractMethod<
    [
      _userId: string,
      _userName: string,
      _action: string,
      _permissionsInToken: string
    ],
    [void],
    "nonpayable"
  >;

  removeAuditor: TypedContractMethod<
    [_auditor: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addAuditor"
  ): TypedContractMethod<[_auditor: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "auditors"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "getAllViolations"
  ): TypedContractMethod<[], [ViolationLogger.ViolationStructOutput[]], "view">;
  getFunction(
    nameOrSignature: "getTotalViolations"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getViolationsByUser"
  ): TypedContractMethod<
    [_userId: string],
    [ViolationLogger.ViolationStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "recordViolation"
  ): TypedContractMethod<
    [
      _userId: string,
      _userName: string,
      _action: string,
      _permissionsInToken: string
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "removeAuditor"
  ): TypedContractMethod<[_auditor: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "AuditorAdded"
  ): TypedContractEvent<
    AuditorAddedEvent.InputTuple,
    AuditorAddedEvent.OutputTuple,
    AuditorAddedEvent.OutputObject
  >;
  getEvent(
    key: "AuditorRemoved"
  ): TypedContractEvent<
    AuditorRemovedEvent.InputTuple,
    AuditorRemovedEvent.OutputTuple,
    AuditorRemovedEvent.OutputObject
  >;
  getEvent(
    key: "ViolationRecorded"
  ): TypedContractEvent<
    ViolationRecordedEvent.InputTuple,
    ViolationRecordedEvent.OutputTuple,
    ViolationRecordedEvent.OutputObject
  >;

  filters: {
    "AuditorAdded(address)": TypedContractEvent<
      AuditorAddedEvent.InputTuple,
      AuditorAddedEvent.OutputTuple,
      AuditorAddedEvent.OutputObject
    >;
    AuditorAdded: TypedContractEvent<
      AuditorAddedEvent.InputTuple,
      AuditorAddedEvent.OutputTuple,
      AuditorAddedEvent.OutputObject
    >;

    "AuditorRemoved(address)": TypedContractEvent<
      AuditorRemovedEvent.InputTuple,
      AuditorRemovedEvent.OutputTuple,
      AuditorRemovedEvent.OutputObject
    >;
    AuditorRemoved: TypedContractEvent<
      AuditorRemovedEvent.InputTuple,
      AuditorRemovedEvent.OutputTuple,
      AuditorRemovedEvent.OutputObject
    >;

    "ViolationRecorded(string,string,uint256)": TypedContractEvent<
      ViolationRecordedEvent.InputTuple,
      ViolationRecordedEvent.OutputTuple,
      ViolationRecordedEvent.OutputObject
    >;
    ViolationRecorded: TypedContractEvent<
      ViolationRecordedEvent.InputTuple,
      ViolationRecordedEvent.OutputTuple,
      ViolationRecordedEvent.OutputObject
    >;
  };
}
